{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b2ed7c75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: sagemaker in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (2.126.0)\n",
      "Requirement already satisfied: google-pasta in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (0.2.0)\n",
      "Requirement already satisfied: attrs<23,>=20.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (21.2.0)\n",
      "Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (1.0.1)\n",
      "Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (1.3.4)\n",
      "Requirement already satisfied: protobuf3-to-dict<1.0,>=0.1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (0.1.5)\n",
      "Requirement already satisfied: importlib-metadata<5.0,>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (4.8.2)\n",
      "Requirement already satisfied: boto3<2.0,>=1.26.28 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (1.26.35)\n",
      "Requirement already satisfied: pathos in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (0.2.8)\n",
      "Requirement already satisfied: numpy<2.0,>=1.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (1.20.3)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (21.3)\n",
      "Requirement already satisfied: schema in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (0.7.5)\n",
      "Requirement already satisfied: protobuf<4.0,>=3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from sagemaker) (3.19.1)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from boto3<2.0,>=1.26.28->sagemaker) (0.10.0)\n",
      "Requirement already satisfied: botocore<1.30.0,>=1.29.35 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from boto3<2.0,>=1.26.28->sagemaker) (1.29.37)\n",
      "Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from boto3<2.0,>=1.26.28->sagemaker) (0.6.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from importlib-metadata<5.0,>=1.4.0->sagemaker) (3.6.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from packaging>=20.0->sagemaker) (3.0.6)\n",
      "Requirement already satisfied: six in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from protobuf3-to-dict<1.0,>=0.1.5->sagemaker) (1.16.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pandas->sagemaker) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2017.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pandas->sagemaker) (2021.3)\n",
      "Requirement already satisfied: multiprocess>=0.70.12 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pathos->sagemaker) (0.70.12.2)\n",
      "Requirement already satisfied: dill>=0.3.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pathos->sagemaker) (0.3.4)\n",
      "Requirement already satisfied: ppft>=1.6.6.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pathos->sagemaker) (1.6.6.4)\n",
      "Requirement already satisfied: pox>=0.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from pathos->sagemaker) (0.3.0)\n",
      "Requirement already satisfied: contextlib2>=0.5.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from schema->sagemaker) (21.6.0)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from botocore<1.30.0,>=1.29.35->boto3<2.0,>=1.26.28->sagemaker) (1.26.8)\n",
      "\u001b[33mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\n",
      "You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install -U sagemaker"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2a96a6fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker\n",
    "import boto3\n",
    "from sagemaker.huggingface import HuggingFace\n",
    "from sagemaker.experiments.run import Run"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "18fa50d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:botocore.credentials:Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole\n",
      "INFO:botocore.credentials:Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole\n"
     ]
    }
   ],
   "source": [
    "sess = sagemaker.Session()\n",
    "role = sagemaker.get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "907d3215",
   "metadata": {},
   "outputs": [],
   "source": [
    "hyperparameters = {\n",
    "    'model_name_or_path':'t5-small',\n",
    "    'epochs':1,\n",
    "    # add your remaining hyperparameters\n",
    "}\n",
    "\n",
    "env = {\n",
    "    'SAGEMAKER_REQUIREMENTS': 'requirements.txt',\n",
    "}\n",
    "exp_name = \"text-summarization-script-mode-experiment\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "be624f31",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:botocore.credentials:Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole\n",
      "INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.\n",
      "INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.\n",
      "INFO:sagemaker:Creating training-job with name: huggingface-tensorflow-training-2022-12-28-16-54-08-631\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-12-28 16:54:09 Starting - Starting the training job...\n",
      "2022-12-28 16:54:34 Starting - Preparing the instances for training.........\n",
      "2022-12-28 16:56:00 Downloading - Downloading input data\n",
      "2022-12-28 16:56:00 Training - Downloading the training image.....................\n",
      "2022-12-28 16:59:32 Training - Training image download completed. Training in progress...\u001b[34m2022-12-28 16:59:48.922615: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.\u001b[0m\n",
      "\u001b[34m2022-12-28 16:59:48.922863: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.\u001b[0m\n",
      "\u001b[34m2022-12-28 16:59:48.974549: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.\u001b[0m\n",
      "\u001b[34m2022-12-28 16:59:50,318 sagemaker-training-toolkit INFO     Imported framework sagemaker_tensorflow_container.training\u001b[0m\n",
      "\u001b[34m2022-12-28 16:59:50,546 sagemaker-training-toolkit INFO     Installing dependencies from requirements.txt:\u001b[0m\n",
      "\u001b[34m/usr/local/bin/python3.8 -m pip install -r requirements.txt\u001b[0m\n",
      "\u001b[34mCollecting evaluate\u001b[0m\n",
      "\u001b[34mDownloading evaluate-0.4.0-py3-none-any.whl (81 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 15.2 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mCollecting rouge-score\u001b[0m\n",
      "\u001b[34mDownloading rouge_score-0.1.2.tar.gz (17 kB)\u001b[0m\n",
      "\u001b[34mPreparing metadata (setup.py): started\u001b[0m\n",
      "\u001b[34mPreparing metadata (setup.py): finished with status 'done'\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: sagemaker in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.96.1.dev0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (4.64.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (2022.5.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: multiprocess in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (0.70.13)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (2.27.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (0.8.1)\u001b[0m\n",
      "\u001b[34mCollecting datasets>=2.0.0\u001b[0m\n",
      "\u001b[34mDownloading datasets-2.8.0-py3-none-any.whl (452 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.9/452.9 kB 10.1 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: packaging in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (21.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (1.19.5)\u001b[0m\n",
      "\u001b[34mCollecting responses<0.19\u001b[0m\n",
      "\u001b[34mDownloading responses-0.18.0-py3-none-any.whl (38 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pandas in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (1.2.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: xxhash in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (3.0.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: dill in /usr/local/lib/python3.8/site-packages (from evaluate->-r requirements.txt (line 1)) (0.3.5.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: absl-py in /usr/local/lib/python3.8/site-packages (from rouge-score->-r requirements.txt (line 2)) (0.15.0)\u001b[0m\n",
      "\u001b[34mCollecting nltk\u001b[0m\n",
      "\u001b[34mDownloading nltk-3.8-py3-none-any.whl (1.5 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 27.1 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.8/site-packages (from rouge-score->-r requirements.txt (line 2)) (1.15.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: importlib-metadata<5.0,>=1.4.0 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (4.12.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: google-pasta in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (0.2.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: attrs<22,>=20.3.0 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (21.4.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pathos in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (0.2.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: boto3<2.0,>=1.20.21 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (1.24.22)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf<4.0,>=3.1 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (3.19.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf3-to-dict<1.0,>=0.1.5 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (0.1.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: smdebug-rulesconfig==1.0.1 in /usr/local/lib/python3.8/site-packages (from sagemaker->-r requirements.txt (line 3)) (1.0.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.8/site-packages (from boto3<2.0,>=1.20.21->sagemaker->-r requirements.txt (line 3)) (0.10.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/site-packages (from boto3<2.0,>=1.20.21->sagemaker->-r requirements.txt (line 3)) (0.6.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: botocore<1.28.0,>=1.27.22 in /usr/local/lib/python3.8/site-packages (from boto3<2.0,>=1.20.21->sagemaker->-r requirements.txt (line 3)) (1.27.22)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: aiohttp in /usr/local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (3.8.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyarrow>=6.0.0 in /usr/local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (8.0.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (5.4.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: filelock in /usr/local/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate->-r requirements.txt (line 1)) (3.7.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate->-r requirements.txt (line 1)) (3.7.4.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/site-packages (from importlib-metadata<5.0,>=1.4.0->sagemaker->-r requirements.txt (line 3)) (3.8.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging->evaluate->-r requirements.txt (line 1)) (3.0.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/site-packages (from requests>=2.19.0->evaluate->-r requirements.txt (line 1)) (2.0.12)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests>=2.19.0->evaluate->-r requirements.txt (line 1)) (2022.6.15)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests>=2.19.0->evaluate->-r requirements.txt (line 1)) (3.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests>=2.19.0->evaluate->-r requirements.txt (line 1)) (1.26.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: joblib in /usr/local/lib/python3.8/site-packages (from nltk->rouge-score->-r requirements.txt (line 2)) (1.1.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: click in /usr/local/lib/python3.8/site-packages (from nltk->rouge-score->-r requirements.txt (line 2)) (8.1.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/site-packages (from nltk->rouge-score->-r requirements.txt (line 2)) (2022.7.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/site-packages (from pandas->evaluate->-r requirements.txt (line 1)) (2022.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/site-packages (from pandas->evaluate->-r requirements.txt (line 1)) (2.8.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: ppft>=1.7.6.5 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker->-r requirements.txt (line 3)) (1.7.6.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pox>=0.3.1 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker->-r requirements.txt (line 3)) (0.3.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (1.2.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (6.0.2)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (1.3.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (1.7.2)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate->-r requirements.txt (line 1)) (4.0.2)\u001b[0m\n",
      "\u001b[34mBuilding wheels for collected packages: rouge-score\u001b[0m\n",
      "\u001b[34mBuilding wheel for rouge-score (setup.py): started\u001b[0m\n",
      "\u001b[34mBuilding wheel for rouge-score (setup.py): finished with status 'done'\u001b[0m\n",
      "\u001b[34mCreated wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24936 sha256=15ba9855864e69e836bafe8de5c0026990ea3462e7a303c8c0b4edb790d88d06\u001b[0m\n",
      "\u001b[34mStored in directory: /root/.cache/pip/wheels/24/55/6f/ebfc4cb176d1c9665da4e306e1705496206d08215c1acd9dde\u001b[0m\n",
      "\u001b[34mSuccessfully built rouge-score\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mInstalling collected packages: nltk, rouge-score, responses, datasets, evaluate\u001b[0m\n",
      "\u001b[34mAttempting uninstall: datasets\u001b[0m\n",
      "\u001b[34mFound existing installation: datasets 1.18.2\u001b[0m\n",
      "\u001b[34mUninstalling datasets-1.18.2:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled datasets-1.18.2\u001b[0m\n",
      "\u001b[34mSuccessfully installed datasets-2.8.0 evaluate-0.4.0 nltk-3.8 responses-0.18.0 rouge-score-0.1.2\u001b[0m\n",
      "\u001b[34mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n",
      "\u001b[34m[notice] A new release of pip available: 22.1.2 -> 22.3.1\u001b[0m\n",
      "\u001b[34m[notice] To update, run: pip install --upgrade pip\u001b[0m\n",
      "\u001b[34m2022-12-28 17:00:02,445 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.\u001b[0m\n",
      "\u001b[34m2022-12-28 17:00:02,446 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.\u001b[0m\n",
      "\u001b[34m2022-12-28 17:00:02,586 sagemaker-training-toolkit INFO     Invoking user script\u001b[0m\n",
      "\u001b[34mTraining Env:\u001b[0m\n",
      "\u001b[34m{\n",
      "    \"additional_framework_parameters\": {},\n",
      "    \"channel_input_dirs\": {},\n",
      "    \"current_host\": \"algo-1\",\n",
      "    \"current_instance_group\": \"homogeneousCluster\",\n",
      "    \"current_instance_group_hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"current_instance_type\": \"ml.p3.2xlarge\",\n",
      "    \"distribution_hosts\": [],\n",
      "    \"distribution_instance_groups\": [],\n",
      "    \"framework_module\": \"sagemaker_tensorflow_container.training:main\",\n",
      "    \"hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"hyperparameters\": {\n",
      "        \"epochs\": 1,\n",
      "        \"model_name_or_path\": \"t5-small\"\n",
      "    },\n",
      "    \"input_config_dir\": \"/opt/ml/input/config\",\n",
      "    \"input_data_config\": {},\n",
      "    \"input_dir\": \"/opt/ml/input\",\n",
      "    \"instance_groups\": [\n",
      "        \"homogeneousCluster\"\n",
      "    ],\n",
      "    \"instance_groups_dict\": {\n",
      "        \"homogeneousCluster\": {\n",
      "            \"instance_group_name\": \"homogeneousCluster\",\n",
      "            \"instance_type\": \"ml.p3.2xlarge\",\n",
      "            \"hosts\": [\n",
      "                \"algo-1\"\n",
      "            ]\n",
      "        }\n",
      "    },\n",
      "    \"is_hetero\": false,\n",
      "    \"is_master\": true,\n",
      "    \"job_name\": \"huggingface-tensorflow-training-2022-12-28-16-54-08-631\",\n",
      "    \"log_level\": 20,\n",
      "    \"master_hostname\": \"algo-1\",\n",
      "    \"model_dir\": \"/opt/ml/model\",\n",
      "    \"module_dir\": \"s3://sagemaker-us-east-1-179099335435/huggingface-tensorflow-training-2022-12-28-16-54-08-631/source/sourcedir.tar.gz\",\n",
      "    \"module_name\": \"train\",\n",
      "    \"network_interface_name\": \"eth0\",\n",
      "    \"num_cpus\": 8,\n",
      "    \"num_gpus\": 1,\n",
      "    \"output_data_dir\": \"/opt/ml/output/data\",\n",
      "    \"output_dir\": \"/opt/ml/output\",\n",
      "    \"output_intermediate_dir\": \"/opt/ml/output/intermediate\",\n",
      "    \"resource_config\": {\n",
      "        \"current_host\": \"algo-1\",\n",
      "        \"current_instance_type\": \"ml.p3.2xlarge\",\n",
      "        \"current_group_name\": \"homogeneousCluster\",\n",
      "        \"hosts\": [\n",
      "            \"algo-1\"\n",
      "        ],\n",
      "        \"instance_groups\": [\n",
      "            {\n",
      "                \"instance_group_name\": \"homogeneousCluster\",\n",
      "                \"instance_type\": \"ml.p3.2xlarge\",\n",
      "                \"hosts\": [\n",
      "                    \"algo-1\"\n",
      "                ]\n",
      "            }\n",
      "        ],\n",
      "        \"network_interface_name\": \"eth0\"\n",
      "    },\n",
      "    \"user_entry_point\": \"train.py\"\u001b[0m\n",
      "\u001b[34m}\u001b[0m\n",
      "\u001b[34mEnvironment variables:\u001b[0m\n",
      "\u001b[34mSM_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_NETWORK_INTERFACE_NAME=eth0\u001b[0m\n",
      "\u001b[34mSM_HPS={\"epochs\":1,\"model_name_or_path\":\"t5-small\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ENTRY_POINT=train.py\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_PARAMS={}\u001b[0m\n",
      "\u001b[34mSM_RESOURCE_CONFIG={\"current_group_name\":\"homogeneousCluster\",\"current_host\":\"algo-1\",\"current_instance_type\":\"ml.p3.2xlarge\",\"hosts\":[\"algo-1\"],\"instance_groups\":[{\"hosts\":[\"algo-1\"],\"instance_group_name\":\"homogeneousCluster\",\"instance_type\":\"ml.p3.2xlarge\"}],\"network_interface_name\":\"eth0\"}\u001b[0m\n",
      "\u001b[34mSM_INPUT_DATA_CONFIG={}\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DATA_DIR=/opt/ml/output/data\u001b[0m\n",
      "\u001b[34mSM_CHANNELS=[]\u001b[0m\n",
      "\u001b[34mSM_CURRENT_HOST=algo-1\u001b[0m\n",
      "\u001b[34mSM_CURRENT_INSTANCE_TYPE=ml.p3.2xlarge\u001b[0m\n",
      "\u001b[34mSM_CURRENT_INSTANCE_GROUP=homogeneousCluster\u001b[0m\n",
      "\u001b[34mSM_CURRENT_INSTANCE_GROUP_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_INSTANCE_GROUPS=[\"homogeneousCluster\"]\u001b[0m\n",
      "\u001b[34mSM_INSTANCE_GROUPS_DICT={\"homogeneousCluster\":{\"hosts\":[\"algo-1\"],\"instance_group_name\":\"homogeneousCluster\",\"instance_type\":\"ml.p3.2xlarge\"}}\u001b[0m\n",
      "\u001b[34mSM_DISTRIBUTION_INSTANCE_GROUPS=[]\u001b[0m\n",
      "\u001b[34mSM_IS_HETERO=false\u001b[0m\n",
      "\u001b[34mSM_MODULE_NAME=train\u001b[0m\n",
      "\u001b[34mSM_LOG_LEVEL=20\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_MODULE=sagemaker_tensorflow_container.training:main\u001b[0m\n",
      "\u001b[34mSM_INPUT_DIR=/opt/ml/input\u001b[0m\n",
      "\u001b[34mSM_INPUT_CONFIG_DIR=/opt/ml/input/config\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DIR=/opt/ml/output\u001b[0m\n",
      "\u001b[34mSM_NUM_CPUS=8\u001b[0m\n",
      "\u001b[34mSM_NUM_GPUS=1\u001b[0m\n",
      "\u001b[34mSM_MODEL_DIR=/opt/ml/model\u001b[0m\n",
      "\u001b[34mSM_MODULE_DIR=s3://sagemaker-us-east-1-179099335435/huggingface-tensorflow-training-2022-12-28-16-54-08-631/source/sourcedir.tar.gz\u001b[0m\n",
      "\u001b[34mSM_TRAINING_ENV={\"additional_framework_parameters\":{},\"channel_input_dirs\":{},\"current_host\":\"algo-1\",\"current_instance_group\":\"homogeneousCluster\",\"current_instance_group_hosts\":[\"algo-1\"],\"current_instance_type\":\"ml.p3.2xlarge\",\"distribution_hosts\":[],\"distribution_instance_groups\":[],\"framework_module\":\"sagemaker_tensorflow_container.training:main\",\"hosts\":[\"algo-1\"],\"hyperparameters\":{\"epochs\":1,\"model_name_or_path\":\"t5-small\"},\"input_config_dir\":\"/opt/ml/input/config\",\"input_data_config\":{},\"input_dir\":\"/opt/ml/input\",\"instance_groups\":[\"homogeneousCluster\"],\"instance_groups_dict\":{\"homogeneousCluster\":{\"hosts\":[\"algo-1\"],\"instance_group_name\":\"homogeneousCluster\",\"instance_type\":\"ml.p3.2xlarge\"}},\"is_hetero\":false,\"is_master\":true,\"job_name\":\"huggingface-tensorflow-training-2022-12-28-16-54-08-631\",\"log_level\":20,\"master_hostname\":\"algo-1\",\"model_dir\":\"/opt/ml/model\",\"module_dir\":\"s3://sagemaker-us-east-1-179099335435/huggingface-tensorflow-training-2022-12-28-16-54-08-631/source/sourcedir.tar.gz\",\"module_name\":\"train\",\"network_interface_name\":\"eth0\",\"num_cpus\":8,\"num_gpus\":1,\"output_data_dir\":\"/opt/ml/output/data\",\"output_dir\":\"/opt/ml/output\",\"output_intermediate_dir\":\"/opt/ml/output/intermediate\",\"resource_config\":{\"current_group_name\":\"homogeneousCluster\",\"current_host\":\"algo-1\",\"current_instance_type\":\"ml.p3.2xlarge\",\"hosts\":[\"algo-1\"],\"instance_groups\":[{\"hosts\":[\"algo-1\"],\"instance_group_name\":\"homogeneousCluster\",\"instance_type\":\"ml.p3.2xlarge\"}],\"network_interface_name\":\"eth0\"},\"user_entry_point\":\"train.py\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ARGS=[\"--epochs\",\"1\",\"--model_name_or_path\",\"t5-small\"]\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate\u001b[0m\n",
      "\u001b[34mSM_HP_EPOCHS=1\u001b[0m\n",
      "\u001b[34mSM_HP_MODEL_NAME_OR_PATH=t5-small\u001b[0m\n",
      "\u001b[34mPYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/local/lib/python38.zip:/usr/local/lib/python3.8:/usr/local/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/site-packages\u001b[0m\n",
      "\u001b[34mInvoking script with the following command:\u001b[0m\n",
      "\u001b[34m/usr/local/bin/python3.8 train.py --epochs 1 --model_name_or_path t5-small\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: sagemaker in /usr/local/lib/python3.8/site-packages (2.96.1.dev0)\u001b[0m\n",
      "\u001b[34mCollecting sagemaker\u001b[0m\n",
      "\u001b[34mDownloading sagemaker-2.126.0.tar.gz (654 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 654.9/654.9 kB 669.8 kB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mPreparing metadata (setup.py): started\u001b[0m\n",
      "\u001b[34mPreparing metadata (setup.py): finished with status 'done'\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: attrs<23,>=20.3.0 in /usr/local/lib/python3.8/site-packages (from sagemaker) (21.4.0)\u001b[0m\n",
      "\u001b[34mCollecting boto3<2.0,>=1.26.28\u001b[0m\n",
      "\u001b[34mDownloading boto3-1.26.38-py3-none-any.whl (132 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.7/132.7 kB 19.3 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: google-pasta in /usr/local/lib/python3.8/site-packages (from sagemaker) (0.2.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: numpy<2.0,>=1.9.0 in /usr/local/lib/python3.8/site-packages (from sagemaker) (1.19.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf<4.0,>=3.1 in /usr/local/lib/python3.8/site-packages (from sagemaker) (3.19.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf3-to-dict<1.0,>=0.1.5 in /usr/local/lib/python3.8/site-packages (from sagemaker) (0.1.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: smdebug_rulesconfig==1.0.1 in /usr/local/lib/python3.8/site-packages (from sagemaker) (1.0.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: importlib-metadata<5.0,>=1.4.0 in /usr/local/lib/python3.8/site-packages (from sagemaker) (4.12.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/site-packages (from sagemaker) (21.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pandas in /usr/local/lib/python3.8/site-packages (from sagemaker) (1.2.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pathos in /usr/local/lib/python3.8/site-packages (from sagemaker) (0.2.9)\u001b[0m\n",
      "\u001b[34mCollecting schema\u001b[0m\n",
      "\u001b[34mDownloading schema-0.7.5-py2.py3-none-any.whl (17 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.8/site-packages (from boto3<2.0,>=1.26.28->sagemaker) (0.10.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/site-packages (from boto3<2.0,>=1.26.28->sagemaker) (0.6.0)\u001b[0m\n",
      "\u001b[34mCollecting botocore<1.30.0,>=1.29.38\u001b[0m\n",
      "\u001b[34mDownloading botocore-1.29.38-py3-none-any.whl (10.3 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 66.8 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/site-packages (from importlib-metadata<5.0,>=1.4.0->sagemaker) (3.8.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging>=20.0->sagemaker) (3.0.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: six in /usr/local/lib/python3.8/site-packages (from protobuf3-to-dict<1.0,>=0.1.5->sagemaker) (1.15.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/site-packages (from pandas->sagemaker) (2022.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/site-packages (from pandas->sagemaker) (2.8.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: ppft>=1.7.6.5 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker) (1.7.6.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pox>=0.3.1 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker) (0.3.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: multiprocess>=0.70.13 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker) (0.70.13)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: dill>=0.3.5.1 in /usr/local/lib/python3.8/site-packages (from pathos->sagemaker) (0.3.5.1)\u001b[0m\n",
      "\u001b[34mCollecting contextlib2>=0.5.5\u001b[0m\n",
      "\u001b[34mDownloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.8/site-packages (from botocore<1.30.0,>=1.29.38->boto3<2.0,>=1.26.28->sagemaker) (1.26.9)\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mBuilding wheels for collected packages: sagemaker\u001b[0m\n",
      "\u001b[34mBuilding wheel for sagemaker (setup.py): started\u001b[0m\n",
      "\u001b[34mBuilding wheel for sagemaker (setup.py): finished with status 'done'\u001b[0m\n",
      "\u001b[34mCreated wheel for sagemaker: filename=sagemaker-2.126.0-py2.py3-none-any.whl size=890071 sha256=927b48aff47d079adc1abee5457c793ea7e0ec1a361ad5719c14915734bf5553\u001b[0m\n",
      "\u001b[34mStored in directory: /root/.cache/pip/wheels/2f/4e/63/345e2f96c60d3f77a2b8be1182a430341092f763b4479dc578\u001b[0m\n",
      "\u001b[34mSuccessfully built sagemaker\u001b[0m\n",
      "\u001b[34mInstalling collected packages: contextlib2, schema, botocore, boto3, sagemaker\u001b[0m\n",
      "\u001b[34mAttempting uninstall: botocore\u001b[0m\n",
      "\u001b[34mFound existing installation: botocore 1.27.22\u001b[0m\n",
      "\u001b[34mUninstalling botocore-1.27.22:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled botocore-1.27.22\u001b[0m\n",
      "\u001b[34mAttempting uninstall: boto3\u001b[0m\n",
      "\u001b[34mFound existing installation: boto3 1.24.22\u001b[0m\n",
      "\u001b[34mUninstalling boto3-1.24.22:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled boto3-1.24.22\u001b[0m\n",
      "\u001b[34mAttempting uninstall: sagemaker\u001b[0m\n",
      "\u001b[34mFound existing installation: sagemaker 2.96.1.dev0\u001b[0m\n",
      "\u001b[34mUninstalling sagemaker-2.96.1.dev0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled sagemaker-2.96.1.dev0\u001b[0m\n",
      "\u001b[34mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\u001b[0m\n",
      "\u001b[34mawscli 1.25.22 requires botocore==1.27.22, but you have botocore 1.29.38 which is incompatible.\u001b[0m\n",
      "\u001b[34mSuccessfully installed boto3-1.26.38 botocore-1.29.38 contextlib2-21.6.0 sagemaker-2.126.0 schema-0.7.5\u001b[0m\n",
      "\u001b[34mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n",
      "\u001b[34m[notice] A new release of pip available: 22.1.2 -> 22.3.1\u001b[0m\n",
      "\u001b[34m[notice] To update, run: pip install --upgrade pip\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: transformers in /usr/local/lib/python3.8/site-packages (4.17.0)\u001b[0m\n",
      "\u001b[34mCollecting transformers\u001b[0m\n",
      "\u001b[34mDownloading transformers-4.25.1-py3-none-any.whl (5.8 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 29.6 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/site-packages (from transformers) (4.64.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/site-packages (from transformers) (5.4.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from transformers) (2.27.1)\u001b[0m\n",
      "\u001b[34mCollecting huggingface-hub<1.0,>=0.10.0\u001b[0m\n",
      "\u001b[34mDownloading huggingface_hub-0.11.1-py3-none-any.whl (182 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 kB 27.8 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/site-packages (from transformers) (1.19.5)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: filelock in /usr/local/lib/python3.8/site-packages (from transformers) (3.7.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/site-packages (from transformers) (21.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.8/site-packages (from transformers) (2022.7.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.8/site-packages (from transformers) (0.12.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.10.0->transformers) (3.7.4.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging>=20.0->transformers) (3.0.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/site-packages (from requests->transformers) (2.0.12)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->transformers) (3.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->transformers) (1.26.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->transformers) (2022.6.15)\u001b[0m\n",
      "\u001b[34mInstalling collected packages: huggingface-hub, transformers\u001b[0m\n",
      "\u001b[34mAttempting uninstall: huggingface-hub\u001b[0m\n",
      "\u001b[34mFound existing installation: huggingface-hub 0.8.1\u001b[0m\n",
      "\u001b[34mUninstalling huggingface-hub-0.8.1:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled huggingface-hub-0.8.1\u001b[0m\n",
      "\u001b[34mAttempting uninstall: transformers\u001b[0m\n",
      "\u001b[34mFound existing installation: transformers 4.17.0\u001b[0m\n",
      "\u001b[34mUninstalling transformers-4.17.0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled transformers-4.17.0\u001b[0m\n",
      "\u001b[34mSuccessfully installed huggingface-hub-0.11.1 transformers-4.25.1\u001b[0m\n",
      "\u001b[34mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n",
      "\u001b[34m[notice] A new release of pip available: 22.1.2 -> 22.3.1\u001b[0m\n",
      "\u001b[34m[notice] To update, run: pip install --upgrade pip\u001b[0m\n",
      "\u001b[34mCollecting tensorflow\u001b[0m\n",
      "\u001b[34mDownloading tensorflow-2.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.1 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/site-packages (from tensorflow) (3.19.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/site-packages (from tensorflow) (3.3.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.8/site-packages (from tensorflow) (3.7.4.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from tensorflow) (62.6.0)\u001b[0m\n",
      "\u001b[34mCollecting absl-py>=1.0.0\u001b[0m\n",
      "\u001b[34mDownloading absl_py-1.3.0-py3-none-any.whl (124 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 24.3 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.8/site-packages (from tensorflow) (1.12.1)\u001b[0m\n",
      "\u001b[34mCollecting tensorflow-estimator<2.12,>=2.11.0\u001b[0m\n",
      "\u001b[34mDownloading tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 14.9 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mCollecting tensorboard<2.12,>=2.11\u001b[0m\n",
      "\u001b[34mDownloading tensorboard-2.11.0-py3-none-any.whl (6.0 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 34.3 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: packaging in /usr/local/lib/python3.8/site-packages (from tensorflow) (21.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.8/site-packages (from tensorflow) (1.15.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.8/site-packages (from tensorflow) (0.4.0)\u001b[0m\n",
      "\u001b[34mCollecting tensorflow-io-gcs-filesystem>=0.23.1\u001b[0m\n",
      "\u001b[34mDownloading tensorflow_io_gcs_filesystem-0.29.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 34.2 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.8/site-packages (from tensorflow) (1.47.0)\u001b[0m\n",
      "\u001b[34mCollecting flatbuffers>=2.0\u001b[0m\n",
      "\u001b[34mDownloading flatbuffers-22.12.6-py2.py3-none-any.whl (26 kB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/site-packages (from tensorflow) (1.1.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.8/site-packages (from tensorflow) (1.6.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.8/site-packages (from tensorflow) (3.1.0)\u001b[0m\n",
      "\u001b[34mCollecting keras<2.12,>=2.11.0\u001b[0m\n",
      "\u001b[34mDownloading keras-2.11.0-py2.py3-none-any.whl (1.7 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 66.3 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mCollecting libclang>=13.0.0\u001b[0m\n",
      "\u001b[34mDownloading libclang-14.0.6-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 37.6 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.8/site-packages (from tensorflow) (0.2.0)\u001b[0m\n",
      "\u001b[34mCollecting numpy>=1.20\u001b[0m\n",
      "\u001b[34mDownloading numpy-1.24.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)\u001b[0m\n",
      "\u001b[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 54.6 MB/s eta 0:00:00\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow) (0.37.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (3.3.7)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (1.35.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (2.0.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (0.4.6)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (0.6.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (1.8.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (2.27.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging->tensorflow) (3.0.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (4.2.4)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (4.7.2)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (0.2.8)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow) (1.3.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow) (4.12.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (3.3)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (2.0.12)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (2022.6.15)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (1.26.9)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow) (3.8.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (0.4.8)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow) (3.2.0)\u001b[0m\n",
      "\u001b[34mInstalling collected packages: libclang, flatbuffers, tensorflow-io-gcs-filesystem, tensorflow-estimator, numpy, keras, absl-py, tensorboard, tensorflow\u001b[0m\n",
      "\u001b[34mAttempting uninstall: flatbuffers\u001b[0m\n",
      "\u001b[34mFound existing installation: flatbuffers 1.12\u001b[0m\n",
      "\u001b[34mUninstalling flatbuffers-1.12:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled flatbuffers-1.12\u001b[0m\n",
      "\u001b[34mAttempting uninstall: tensorflow-io-gcs-filesystem\u001b[0m\n",
      "\u001b[34mFound existing installation: tensorflow-io-gcs-filesystem 0.21.0\u001b[0m\n",
      "\u001b[34mUninstalling tensorflow-io-gcs-filesystem-0.21.0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled tensorflow-io-gcs-filesystem-0.21.0\u001b[0m\n",
      "\u001b[34mAttempting uninstall: tensorflow-estimator\u001b[0m\n",
      "\u001b[34mFound existing installation: tensorflow-estimator 2.6.0\u001b[0m\n",
      "\u001b[34mUninstalling tensorflow-estimator-2.6.0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled tensorflow-estimator-2.6.0\u001b[0m\n",
      "\u001b[34mAttempting uninstall: numpy\u001b[0m\n",
      "\u001b[34mFound existing installation: numpy 1.19.5\u001b[0m\n",
      "\u001b[34mUninstalling numpy-1.19.5:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled numpy-1.19.5\u001b[0m\n",
      "\u001b[34mAttempting uninstall: keras\u001b[0m\n",
      "\u001b[34mFound existing installation: keras 2.6.0\u001b[0m\n",
      "\u001b[34mUninstalling keras-2.6.0:\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mSuccessfully uninstalled keras-2.6.0\u001b[0m\n",
      "\u001b[34mAttempting uninstall: absl-py\u001b[0m\n",
      "\u001b[34mFound existing installation: absl-py 0.15.0\u001b[0m\n",
      "\u001b[34mUninstalling absl-py-0.15.0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled absl-py-0.15.0\u001b[0m\n",
      "\u001b[34mAttempting uninstall: tensorboard\u001b[0m\n",
      "\u001b[34mFound existing installation: tensorboard 2.6.0\u001b[0m\n",
      "\u001b[34mUninstalling tensorboard-2.6.0:\u001b[0m\n",
      "\u001b[34mSuccessfully uninstalled tensorboard-2.6.0\u001b[0m\n",
      "\u001b[34mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\u001b[0m\n",
      "\u001b[34mtensorflow-io 0.21.0 requires tensorflow<2.7.0,>=2.6.0, but you have tensorflow 2.11.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-io 0.21.0 requires tensorflow-io-gcs-filesystem==0.21.0, but you have tensorflow-io-gcs-filesystem 0.29.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires absl-py~=0.10, but you have absl-py 1.3.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires flatbuffers~=1.12.0, but you have flatbuffers 22.12.6 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires keras<2.7,>=2.6.0, but you have keras 2.11.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires numpy~=1.19.2, but you have numpy 1.24.1 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires tensorboard<2.7,>=2.6.0, but you have tensorboard 2.11.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mtensorflow-gpu 2.6.3 requires tensorflow-estimator<2.7,>=2.6.0, but you have tensorflow-estimator 2.11.0 which is incompatible.\u001b[0m\n",
      "\u001b[34mscipy 1.7.0 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.1 which is incompatible.\u001b[0m\n",
      "\u001b[34mnumba 0.55.2 requires numpy<1.23,>=1.18, but you have numpy 1.24.1 which is incompatible.\u001b[0m\n",
      "\u001b[34mSuccessfully installed absl-py-1.3.0 flatbuffers-22.12.6 keras-2.11.0 libclang-14.0.6 numpy-1.24.1 tensorboard-2.11.0 tensorflow-2.11.0 tensorflow-estimator-2.11.0 tensorflow-io-gcs-filesystem-0.29.0\u001b[0m\n",
      "\u001b[34mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n",
      "\u001b[34m[notice] A new release of pip available: 22.1.2 -> 22.3.1\u001b[0m\n",
      "\u001b[34m[notice] To update, run: pip install --upgrade pip\u001b[0m\n",
      "\u001b[34m2022-12-28 17:01:15.590283: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/site-packages/smdistributed/dataparallel/lib:/usr/local/lib:/opt/amazon/openmpi/lib/:/opt/amazon/efa/lib/:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\u001b[0m\n",
      "\u001b[34m2022-12-28 17:01:15.590454: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/site-packages/smdistributed/dataparallel/lib:/usr/local/lib:/opt/amazon/openmpi/lib/:/opt/amazon/efa/lib/:/usr/local/nvidia/lib:/usr/local/nvidia/lib64\u001b[0m\n",
      "\u001b[34m2022-12-28 17:01:15.590467: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\u001b[0m\n",
      "\u001b[34m/usr/local/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1\n",
      "  warnings.warn(f\"A NumPy version >={np_minversion} and <{np_maxversion}\"\u001b[0m\n",
      "\u001b[34mDownloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading builder script: 100%|██████████| 6.27k/6.27k [00:00<00:00, 6.76MB/s]\u001b[0m\n",
      "\u001b[34mRead Training Data\u001b[0m\n",
      "\u001b[34mDownloading readme:   0%|          | 0.00/3.33k [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading readme: 100%|██████████| 3.33k/3.33k [00:00<00:00, 3.65MB/s]\u001b[0m\n",
      "\u001b[34mWARNING:datasets.builder:Using custom data configuration kmfoda--booksum-025141c210e07407\u001b[0m\n",
      "\u001b[34mDownloading and preparing dataset csv/kmfoda--booksum to /root/.cache/huggingface/datasets/kmfoda___csv/kmfoda--booksum-025141c210e07407/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317...\u001b[0m\n",
      "\u001b[34mDownloading data files:   0%|          | 0/3 [00:00<?, ?it/s]\u001b[0m\n",
      "\u001b[34mDownloading data:   0%|          | 0.00/295M [00:00<?, ?B/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:   2%|▏         | 5.04M/295M [00:00<00:05, 50.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:   4%|▎         | 11.0M/295M [00:00<00:05, 55.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:   6%|▌         | 17.0M/295M [00:00<00:04, 57.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:   8%|▊         | 22.7M/295M [00:00<00:05, 51.2MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  10%|▉         | 28.6M/295M [00:00<00:04, 53.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  12%|█▏        | 34.6M/295M [00:00<00:04, 55.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  14%|█▎        | 40.3M/295M [00:00<00:05, 49.0MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  16%|█▌        | 45.8M/295M [00:00<00:04, 50.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  17%|█▋        | 51.6M/295M [00:00<00:04, 52.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  19%|█▉        | 57.0M/295M [00:01<00:04, 52.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  21%|██▏       | 62.9M/295M [00:01<00:04, 54.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  23%|██▎       | 68.5M/295M [00:01<00:05, 44.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  25%|██▌       | 74.3M/295M [00:01<00:04, 48.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  27%|██▋       | 79.4M/295M [00:01<00:05, 36.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  29%|██▉       | 85.2M/295M [00:01<00:05, 41.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  31%|███       | 91.1M/295M [00:01<00:04, 45.5MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  33%|███▎      | 96.1M/295M [00:01<00:04, 46.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  35%|███▍      | 102M/295M [00:02<00:03, 49.7MB/s] #033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  37%|███▋      | 108M/295M [00:02<00:03, 52.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  39%|███▊      | 114M/295M [00:02<00:03, 54.2MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  41%|████      | 120M/295M [00:02<00:03, 55.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  43%|████▎     | 126M/295M [00:02<00:02, 57.0MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  45%|████▍     | 132M/295M [00:02<00:02, 57.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  47%|████▋     | 138M/295M [00:02<00:02, 58.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  49%|████▊     | 144M/295M [00:02<00:02, 58.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  51%|█████     | 150M/295M [00:02<00:02, 59.1MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  53%|█████▎    | 156M/295M [00:02<00:02, 59.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  55%|█████▍    | 162M/295M [00:03<00:02, 59.6MB/s]\u001b[0m\n",
      "\u001b[34m#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  57%|█████▋    | 168M/295M [00:03<00:02, 59.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  59%|█████▉    | 174M/295M [00:03<00:02, 59.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  61%|██████    | 180M/295M [00:03<00:01, 60.1MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  63%|██████▎   | 186M/295M [00:03<00:01, 60.2MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  65%|██████▍   | 192M/295M [00:03<00:01, 52.3MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  67%|██████▋   | 197M/295M [00:03<00:01, 51.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  69%|██████▊   | 202M/295M [00:03<00:01, 50.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  70%|███████   | 208M/295M [00:03<00:01, 50.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  72%|███████▏  | 213M/295M [00:04<00:01, 49.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  74%|███████▍  | 218M/295M [00:04<00:01, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  75%|███████▌  | 223M/295M [00:04<00:01, 49.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  77%|███████▋  | 228M/295M [00:04<00:01, 49.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  79%|███████▉  | 233M/295M [00:04<00:01, 49.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  81%|████████  | 238M/295M [00:04<00:01, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  82%|████████▏ | 243M/295M [00:04<00:01, 49.8MB/s]\u001b[0m\n",
      "\u001b[34m#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  84%|████████▍ | 248M/295M [00:04<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  86%|████████▌ | 253M/295M [00:04<00:00, 49.5MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  87%|████████▋ | 258M/295M [00:04<00:00, 49.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  89%|████████▉ | 263M/295M [00:05<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  91%|█████████ | 268M/295M [00:05<00:00, 50.0MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  92%|█████████▏| 273M/295M [00:05<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  94%|█████████▍| 278M/295M [00:05<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  96%|█████████▌| 283M/295M [00:05<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  97%|█████████▋| 288M/295M [00:05<00:00, 49.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  99%|█████████▉| 293M/295M [00:05<00:00, 49.7MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data: 100%|██████████| 295M/295M [00:05<00:00, 51.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading data files:  33%|███▎      | 1/3 [00:06<00:12,  6.01s/it]\u001b[0m\n",
      "\u001b[34mDownloading data:   0%|          | 0.00/43.4M [00:00<?, ?B/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:   9%|▉         | 4.06M/43.4M [00:00<00:00, 40.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  20%|█▉        | 8.53M/43.4M [00:00<00:00, 43.0MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  30%|██▉       | 13.0M/43.4M [00:00<00:00, 43.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  40%|████      | 17.5M/43.4M [00:00<00:00, 44.3MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  51%|█████     | 22.0M/43.4M [00:00<00:00, 44.5MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  61%|██████    | 26.5M/43.4M [00:00<00:00, 44.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  71%|███████▏  | 30.9M/43.4M [00:00<00:00, 44.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  82%|████████▏ | 35.4M/43.4M [00:00<00:00, 44.6MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  92%|█████████▏| 39.9M/43.4M [00:00<00:00, 44.5MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data: 100%|██████████| 43.4M/43.4M [00:00<00:00, 44.3MB/s]\u001b[0m\n",
      "\u001b[34mDownloading data files:  67%|██████▋   | 2/3 [00:07<00:03,  3.21s/it]\u001b[0m\n",
      "\u001b[34mDownloading data:   0%|          | 0.00/40.4M [00:00<?, ?B/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  11%|█         | 4.41M/40.4M [00:00<00:00, 44.1MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  23%|██▎       | 9.29M/40.4M [00:00<00:00, 46.9MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  35%|███▌      | 14.3M/40.4M [00:00<00:00, 48.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  47%|████▋     | 19.2M/40.4M [00:00<00:00, 48.2MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  60%|█████▉    | 24.2M/40.4M [00:00<00:00, 48.8MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  72%|███████▏  | 29.2M/40.4M [00:00<00:00, 49.3MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  85%|████████▍ | 34.1M/40.4M [00:00<00:00, 49.4MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data:  97%|█████████▋| 39.1M/40.4M [00:00<00:00, 49.5MB/s]#033[A\u001b[0m\n",
      "\u001b[34mDownloading data: 100%|██████████| 40.4M/40.4M [00:00<00:00, 49.0MB/s]\u001b[0m\n",
      "\u001b[34mDownloading data files: 100%|██████████| 3/3 [00:08<00:00,  2.24s/it]\u001b[0m\n",
      "\u001b[34mDownloading data files: 100%|██████████| 3/3 [00:08<00:00,  2.78s/it]\u001b[0m\n",
      "\u001b[34mExtracting data files:   0%|          | 0/3 [00:00<?, ?it/s]\u001b[0m\n",
      "\u001b[34mExtracting data files: 100%|██████████| 3/3 [00:00<00:00, 1366.82it/s]\u001b[0m\n",
      "\u001b[34mGenerating train split: 0 examples [00:00, ? examples/s]\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mGenerating train split: 9600 examples [00:02, 3532.19 examples/s]\u001b[0m\n",
      "\u001b[34mGenerating test split: 0 examples [00:00, ? examples/s]\u001b[0m\n",
      "\u001b[34mGenerating test split: 1431 examples [00:00, 3823.36 examples/s]\u001b[0m\n",
      "\u001b[34mGenerating validation split: 0 examples [00:00, ? examples/s]\u001b[0m\n",
      "\u001b[34mGenerating validation split: 1484 examples [00:00, 4821.73 examples/s]\u001b[0m\n",
      "\u001b[34mDataset csv downloaded and prepared to /root/.cache/huggingface/datasets/kmfoda___csv/kmfoda--booksum-025141c210e07407/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317. Subsequent calls will reuse this data.\u001b[0m\n",
      "\u001b[34m0%|          | 0/3 [00:00<?, ?it/s]\u001b[0m\n",
      "\u001b[34m100%|██████████| 3/3 [00:00<00:00, 358.96it/s]\u001b[0m\n",
      "\u001b[34mDownloading:   0%|          | 0.00/1.21k [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading: 100%|██████████| 1.21k/1.21k [00:00<00:00, 938kB/s]\u001b[0m\n",
      "\u001b[34mDownloading:   0%|          | 0.00/792k [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading: 100%|██████████| 792k/792k [00:00<00:00, 33.1MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:   0%|          | 0.00/1.39M [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading: 100%|██████████| 1.39M/1.39M [00:00<00:00, 40.2MB/s]\u001b[0m\n",
      "\u001b[34m/usr/local/lib/python3.8/site-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.\u001b[0m\n",
      "\u001b[34mFor now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.\u001b[0m\n",
      "\u001b[34m- Be aware that you SHOULD NOT rely on t5-small automatically truncating your input to 512 when padding/encoding.\u001b[0m\n",
      "\u001b[34m- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.\u001b[0m\n",
      "\u001b[34m- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.\n",
      "  warnings.warn(\u001b[0m\n",
      "\u001b[34mDownloading:   0%|          | 0.00/242M [00:00<?, ?B/s]\u001b[0m\n",
      "\u001b[34mDownloading:   2%|▏         | 4.40M/242M [00:00<00:05, 44.0MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:   4%|▍         | 9.23M/242M [00:00<00:05, 46.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:   6%|▌         | 13.9M/242M [00:00<00:04, 46.8MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:   8%|▊         | 18.7M/242M [00:00<00:04, 47.2MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  10%|▉         | 23.5M/242M [00:00<00:04, 47.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  12%|█▏        | 28.3M/242M [00:00<00:04, 47.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  14%|█▎        | 33.2M/242M [00:00<00:04, 48.0MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  16%|█▌        | 38.0M/242M [00:00<00:04, 47.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  18%|█▊        | 42.7M/242M [00:00<00:04, 47.3MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  20%|█▉        | 47.5M/242M [00:01<00:04, 47.2MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  22%|██▏       | 52.3M/242M [00:01<00:03, 47.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  24%|██▎       | 57.2M/242M [00:01<00:03, 47.9MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  26%|██▌       | 62.0M/242M [00:01<00:03, 47.9MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  28%|██▊       | 66.8M/242M [00:01<00:03, 48.1MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  30%|██▉       | 71.7M/242M [00:01<00:03, 48.2MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  32%|███▏      | 76.5M/242M [00:01<00:03, 48.3MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  34%|███▎      | 81.4M/242M [00:01<00:03, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  36%|███▌      | 86.2M/242M [00:01<00:03, 48.3MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  38%|███▊      | 91.1M/242M [00:01<00:03, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  40%|███▉      | 96.0M/242M [00:02<00:03, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  42%|████▏     | 101M/242M [00:02<00:02, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  44%|████▎     | 106M/242M [00:02<00:02, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  46%|████▌     | 111M/242M [00:02<00:02, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  48%|████▊     | 115M/242M [00:02<00:02, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  50%|████▉     | 120M/242M [00:02<00:02, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  52%|█████▏    | 125M/242M [00:02<00:02, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  54%|█████▎    | 130M/242M [00:02<00:02, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  56%|█████▌    | 135M/242M [00:02<00:02, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  58%|█████▊    | 140M/242M [00:02<00:02, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  60%|█████▉    | 145M/242M [00:03<00:02, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  62%|██████▏   | 149M/242M [00:03<00:01, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  64%|██████▎   | 154M/242M [00:03<00:01, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  66%|██████▌   | 159M/242M [00:03<00:01, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  68%|██████▊   | 164M/242M [00:03<00:01, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  70%|██████▉   | 169M/242M [00:03<00:01, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  72%|███████▏  | 174M/242M [00:03<00:01, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  74%|███████▍  | 179M/242M [00:03<00:01, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  76%|███████▌  | 184M/242M [00:03<00:01, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  78%|███████▊  | 188M/242M [00:03<00:01, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  80%|███████▉  | 193M/242M [00:04<00:01, 48.4MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  82%|████████▏ | 198M/242M [00:04<00:00, 48.5MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  84%|████████▍ | 203M/242M [00:04<00:00, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  86%|████████▌ | 208M/242M [00:04<00:00, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  88%|████████▊ | 213M/242M [00:04<00:00, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  90%|████████▉ | 218M/242M [00:04<00:00, 48.6MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  92%|█████████▏| 223M/242M [00:04<00:00, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  94%|█████████▍| 227M/242M [00:04<00:00, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  96%|█████████▌| 232M/242M [00:04<00:00, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading:  98%|█████████▊| 237M/242M [00:04<00:00, 48.7MB/s]\u001b[0m\n",
      "\u001b[34mDownloading: 100%|█████████▉| 242M/242M [00:05<00:00, 48.8MB/s]\u001b[0m\n",
      "\u001b[34mDownloading: 100%|██████████| 242M/242M [00:05<00:00, 48.3MB/s]\u001b[0m\n",
      "\u001b[34mAll model checkpoint layers were used when initializing TFT5ForConditionalGeneration.\u001b[0m\n",
      "\u001b[34mAll the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.\u001b[0m\n",
      "\u001b[34mIf your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.\u001b[0m\n",
      "\u001b[34m0%|          | 0/10 [00:00<?, ?ba/s]\u001b[0m\n",
      "\u001b[34m10%|█         | 1/10 [00:07<01:07,  7.55s/ba]\u001b[0m\n",
      "\u001b[34m20%|██        | 2/10 [00:14<00:59,  7.45s/ba]\u001b[0m\n",
      "\u001b[34m30%|███       | 3/10 [00:20<00:45,  6.54s/ba]\u001b[0m\n",
      "\u001b[34m40%|████      | 4/10 [00:28<00:42,  7.07s/ba]\u001b[0m\n",
      "\u001b[34m50%|█████     | 5/10 [00:33<00:31,  6.33s/ba]\u001b[0m\n",
      "\u001b[34m60%|██████    | 6/10 [00:38<00:24,  6.05s/ba]\u001b[0m\n",
      "\u001b[34m70%|███████   | 7/10 [00:44<00:17,  5.97s/ba]\u001b[0m\n",
      "\u001b[34m80%|████████  | 8/10 [00:48<00:10,  5.28s/ba]\u001b[0m\n",
      "\u001b[34m90%|█████████ | 9/10 [00:55<00:05,  5.90s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 10/10 [00:58<00:00,  5.02s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 10/10 [00:58<00:00,  5.87s/ba]\u001b[0m\n",
      "\u001b[34m0%|          | 0/2 [00:00<?, ?ba/s]\u001b[0m\n",
      "\u001b[34m50%|█████     | 1/2 [00:06<00:06,  6.13s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 2/2 [00:09<00:00,  4.47s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 2/2 [00:09<00:00,  4.72s/ba]\u001b[0m\n",
      "\u001b[34m0%|          | 0/2 [00:00<?, ?ba/s]\u001b[0m\n",
      "\u001b[34m50%|█████     | 1/2 [00:06<00:06,  6.45s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 2/2 [00:07<00:00,  3.44s/ba]\u001b[0m\n",
      "\u001b[34m100%|██████████| 2/2 [00:07<00:00,  3.89s/ba]\u001b[0m\n",
      "\u001b[34mYou're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.\u001b[0m\n",
      "\u001b[34mNo loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.\u001b[0m\n",
      "\u001b[34mINFO:sagemaker.experiments.run:The run (sagemaker-run-1672246448-0c9a) under experiment (text-summarization-script-mode-experiment) already exists. Loading it. Note: sagemaker.experiments.load_run is recommended to use when the desired run already exists.\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mLambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mLambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34m2022-12-28 17:03:31.798032: W tensorflow/core/framework/op_kernel.cc:1807] OP_REQUIRES failed at cast_op.cc:121 : UNIMPLEMENTED: Cast string to float is not supported\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:31.798433: W tensorflow/core/framework/op_kernel.cc:1807] OP_REQUIRES failed at cast_op.cc:121 : UNIMPLEMENTED: Cast string to float is not supported\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"train.py\", line 100, in <module>\u001b[0m\n",
      "\u001b[34mtrain_results = model.fit(tf_train_df, validation_data=tf_eval_df, epochs=args.epochs, callbacks=[metric_callback])\n",
      "  File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\u001b[0m\n",
      "\u001b[34mtensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\u001b[0m\n",
      "\u001b[34mtensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\u001b[0m\n",
      "\u001b[34mDetected at node 'Cast_1' defined at (most recent call last):\n",
      "    File \"train.py\", line 100, in <module>\n",
      "      train_results = model.fit(tf_train_df, validation_data=tf_eval_df, epochs=args.epochs, callbacks=[metric_callback])\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "      return fn(*args, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n",
      "      tmp_logs = self.train_function(iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n",
      "      return step_function(self, iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n",
      "      outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n",
      "      outputs = model.train_step(data)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/modeling_tf_utils.py\", line 1557, in train_step\n",
      "      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n",
      "      self.apply_gradients(grads_and_vars)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/optimization_tf.py\", line 246, in apply_gradients\n",
      "      return super(AdamWeightDecay, self).apply_gradients(zip(grads, tvars), name=name, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n",
      "      return super().apply_gradients(grads_and_vars, name=name)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 632, in apply_gradients\n",
      "      self._apply_weight_decay(trainable_variables)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1159, in _apply_weight_decay\n",
      "      tf.__internal__.distribute.interim.maybe_merge_call(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1155, in distributed_apply_weight_decay\n",
      "      distribution.extended.update(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1151, in weight_decay_fn\n",
      "      wd = tf.cast(self.weight_decay, variable.dtype)\u001b[0m\n",
      "\u001b[34mNode: 'Cast_1'\u001b[0m\n",
      "\u001b[34m2 root error(s) found.\n",
      "  (0) UNIMPLEMENTED:  Cast string to float is not supported\u001b[0m\n",
      "\u001b[34m#011 [[{{node Cast_1}}]]\n",
      "  (1) CANCELLED:  Function was cancelled before it was started\u001b[0m\n",
      "\u001b[34m0 successful operations.\u001b[0m\n",
      "\u001b[34m0 derived errors ignored. [Op:__inference_train_function_55390]\u001b[0m\n",
      "\u001b[34mDuring handling of the above exception, another exception occurred:\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"train.py\", line 111, in <module>\u001b[0m\n",
      "\u001b[34mtokenizer.save_pretrained(args.model_dir)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/sagemaker/experiments/run.py\", line 710, in __exit__\u001b[0m\n",
      "\u001b[34mself.close()\n",
      "  File \"/usr/local/lib/python3.8/site-packages/sagemaker/experiments/run.py\", line 507, in close\n",
      "    self._trial_component.save()\n",
      "  File \"/usr/local/lib/python3.8/site-packages/sagemaker/experiments/trial_component.py\", line 119, in save\n",
      "    return self._invoke_api(self._boto_update_method, self._boto_update_members)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/sagemaker/apiutils/_base_types.py\", line 226, in _invoke_api\n",
      "    api_boto_response = api_method(**api_kwargs)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/botocore/client.py\", line 530, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/botocore/client.py\", line 960, in _make_api_call\u001b[0m\n",
      "\u001b[34mraise error_class(parsed_response, operation_name)\u001b[0m\n",
      "\u001b[34mbotocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateTrialComponent operation: 2 validation errors detected: Value 'Graph execution error:\u001b[0m\n",
      "\u001b[34mDetected at node 'Cast_1' defined at (most recent call last):\n",
      "    File \"train.py\", line 100, in <module>\n",
      "      train_results = model.fit(tf_train_df, validation_data=tf_eval_df, epochs=args.epochs, callbacks=[metric_callback])\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "      return fn(*args, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n",
      "      tmp_logs = self.train_function(iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n",
      "      return step_function(self, iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n",
      "      outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n",
      "      outputs = model.train_step(data)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/modeling_tf_utils.py\", line 1557, in train_step\n",
      "      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n",
      "      self.apply_gradients(grads_and_vars)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/optimization_tf.py\", line 246, in apply_gradients\n",
      "      return super(AdamWeightDecay, self).apply_gradients(zip(grads, tvars), name=name, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n",
      "      return super().apply_gradients(grads_and_vars, name=name)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 632, in apply_gradients\n",
      "      self._apply_weight_decay(trainable_variables)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1159, in _apply_weight_decay\n",
      "      tf.__internal__.distribute.interim.maybe_merge_call(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1155, in distributed_apply_weight_decay\n",
      "      distribution.extended.update(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1151, in weight_decay_fn\n",
      "      wd = tf.cast(self.weight_decay, variable.dtype)\u001b[0m\n",
      "\u001b[34mNode: 'Cast_1'\u001b[0m\n",
      "\u001b[34m2 root error(s) found.\n",
      "  (0) UNIMPLEMENTED:  Cast string to float is not supported\u001b[0m\n",
      "\u001b[34m#011 [[{{node Cast_1}}]]\n",
      "  (1) CANCELLED:  Function was cancelled before it was started\u001b[0m\n",
      "\u001b[34m0 successful operations.\u001b[0m\n",
      "\u001b[34m0 derived errors ignored. [Op:__inference_train_function_55390]' at 'status.message' failed to satisfy constraint: Member must have length less than or equal to 1024; Value 'Graph execution error:\u001b[0m\n",
      "\u001b[34mDetected at node 'Cast_1' defined at (most recent call last):\n",
      "    File \"train.py\", line 100, in <module>\n",
      "      train_results = model.fit(tf_train_df, validation_data=tf_eval_df, epochs=args.epochs, callbacks=[metric_callback])\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "      return fn(*args, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1650, in fit\n",
      "      tmp_logs = self.train_function(iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in train_function\n",
      "      return step_function(self, iterator)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1233, in step_function\n",
      "      outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/engine/training.py\", line 1222, in run_step\n",
      "      outputs = model.train_step(data)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/modeling_tf_utils.py\", line 1557, in train_step\n",
      "      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n",
      "      self.apply_gradients(grads_and_vars)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/transformers/optimization_tf.py\", line 246, in apply_gradients\n",
      "      return super(AdamWeightDecay, self).apply_gradients(zip(grads, tvars), name=name, **kwargs)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n",
      "      return super().apply_gradients(grads_and_vars, name=name)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 632, in apply_gradients\n",
      "      self._apply_weight_decay(trainable_variables)\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1159, in _apply_weight_decay\n",
      "      tf.__internal__.distribute.interim.maybe_merge_call(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1155, in distributed_apply_weight_decay\n",
      "      distribution.extended.update(\n",
      "    File \"/usr/local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1151, in weight_decay_fn\n",
      "      wd = tf.cast(self.weight_decay, variable.dtype)\u001b[0m\n",
      "\u001b[34mNode: 'Cast_1'\u001b[0m\n",
      "\u001b[34m2 root error(s) found.\n",
      "  (0) UNIMPLEMENTED:  Cast string to float is not supported\u001b[0m\n",
      "\u001b[34m#011 [[{{node Cast_1}}]]\n",
      "  (1) CANCELLED:  Function was cancelled before it was started\u001b[0m\n",
      "\u001b[34m0 successful operations.\u001b[0m\n",
      "\u001b[34m0 derived errors ignored. [Op:__inference_train_function_55390]' at 'status.message' failed to satisfy constraint: Member must satisfy regular expression pattern: .*\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:33,411 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:33,411 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:33,412 sagemaker-training-toolkit ERROR    Reporting training FAILURE\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:33,412 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mExitCode 1\u001b[0m\n",
      "\u001b[34mErrorMessage \"\"\u001b[0m\n",
      "\u001b[34mCommand \"/usr/local/bin/python3.8 train.py --epochs 1 --model_name_or_path t5-small\"\u001b[0m\n",
      "\u001b[34m2022-12-28 17:03:33,412 sagemaker-training-toolkit ERROR    Encountered exit_code 1\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "2022-12-28 17:03:49 Uploading - Uploading generated training model\n",
      "2022-12-28 17:03:49 Failed - Training job failed\n"
     ]
    },
    {
     "ename": "ClientError",
     "evalue": "An error occurred (ValidationException) when calling the UpdateTrialComponent operation: 1 validation error detected: Value 'Error for Training job huggingface-tensorflow-training-2022-12-28-16-54-08-631: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nExitCode 1\nErrorMessage \"\"\nCommand \"/usr/local/bin/python3.8 train.py --epochs 1 --model_name_or_path t5-small\", exit code: 1' at 'status.message' failed to satisfy constraint: Member must satisfy regular expression pattern: .*",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_24517/1051652476.py\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     14\u001b[0m                             hyperparameters = hyperparameters)\n\u001b[0;32m---> 15\u001b[0;31m     \u001b[0mhuggingface_estimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/workflow/pipeline_context.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    271\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 272\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mrun_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    273\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m   1132\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1133\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1134\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   2248\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2249\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2250\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   4112\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 4113\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   4114\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   3643\u001b[0m                 )\n\u001b[0;32m-> 3644\u001b[0;31m             raise exceptions.UnexpectedStatusException(\n\u001b[0m\u001b[1;32m   3645\u001b[0m                 \u001b[0mmessage\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmessage\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job huggingface-tensorflow-training-2022-12-28-16-54-08-631: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nExitCode 1\nErrorMessage \"\"\nCommand \"/usr/local/bin/python3.8 train.py --epochs 1 --model_name_or_path t5-small\", exit code: 1",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mClientError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_24517/1051652476.py\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m                             \u001b[0menv\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0menv\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m                             hyperparameters = hyperparameters)\n\u001b[0;32m---> 15\u001b[0;31m     \u001b[0mhuggingface_estimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/experiments/run.py\u001b[0m in \u001b[0;36m__exit__\u001b[0;34m(self, exc_type, exc_value, exc_traceback)\u001b[0m\n\u001b[1;32m    708\u001b[0m             )\n\u001b[1;32m    709\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 710\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    711\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    712\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/experiments/run.py\u001b[0m in \u001b[0;36mclose\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    505\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    506\u001b[0m             \u001b[0;31m# Update the trial component with additions from the Run object\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 507\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_trial_component\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msave\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    508\u001b[0m             \u001b[0;31m# Create Lineage entities for the artifacts\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    509\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_lineage_artifact_tracker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msave\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/experiments/trial_component.py\u001b[0m in \u001b[0;36msave\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    117\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0msave\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    118\u001b[0m         \u001b[0;34m\"\"\"Save the state of this TrialComponent to SageMaker.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 119\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_invoke_api\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_boto_update_method\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_boto_update_members\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    120\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    121\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mdelete\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mforce_disassociate\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/sagemaker/apiutils/_base_types.py\u001b[0m in \u001b[0;36m_invoke_api\u001b[0;34m(self, boto_method, boto_method_members)\u001b[0m\n\u001b[1;32m    224\u001b[0m         \u001b[0mapi_kwargs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_boto\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mapi_values\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    225\u001b[0m         \u001b[0mapi_method\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mboto_method\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 226\u001b[0;31m         \u001b[0mapi_boto_response\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mapi_method\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mapi_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    227\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_boto\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mapi_boto_response\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/botocore/client.py\u001b[0m in \u001b[0;36m_api_call\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    528\u001b[0m                 )\n\u001b[1;32m    529\u001b[0m             \u001b[0;31m# The \"self\" in this scope is referring to the BaseClient.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 530\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_api_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moperation_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    531\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    532\u001b[0m         \u001b[0m_api_call\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpy_operation_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.8/site-packages/botocore/client.py\u001b[0m in \u001b[0;36m_make_api_call\u001b[0;34m(self, operation_name, api_params)\u001b[0m\n\u001b[1;32m    958\u001b[0m             \u001b[0merror_code\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Error\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Code\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    959\u001b[0m             \u001b[0merror_class\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_code\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror_code\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 960\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0merror_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparsed_response\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moperation_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    961\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    962\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mClientError\u001b[0m: An error occurred (ValidationException) when calling the UpdateTrialComponent operation: 1 validation error detected: Value 'Error for Training job huggingface-tensorflow-training-2022-12-28-16-54-08-631: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nExitCode 1\nErrorMessage \"\"\nCommand \"/usr/local/bin/python3.8 train.py --epochs 1 --model_name_or_path t5-small\", exit code: 1' at 'status.message' failed to satisfy constraint: Member must satisfy regular expression pattern: .*"
     ]
    }
   ],
   "source": [
    "with Run(experiment_name=exp_name, sagemaker_session=sess) as run:\n",
    "    run.log_parameter(\"epochs\", hyperparameters['epochs'])\n",
    "    run.log_parameter(\"model_name\", hyperparameters['model_name_or_path'])\n",
    "    \n",
    "    huggingface_estimator = HuggingFace(entry_point='train.py',\n",
    "                            source_dir='./scripts',\n",
    "                            instance_type='ml.p3.2xlarge',\n",
    "                            instance_count=1,\n",
    "                            role=role,\n",
    "                            transformers_version='4.17',\n",
    "                            tensorflow_version='2.6',\n",
    "                            py_version='py38',\n",
    "                            env=env,\n",
    "                            hyperparameters = hyperparameters)\n",
    "    huggingface_estimator.fit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7c97417",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
